server:
  port: 80
  servlet:
    context-path: /

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
  #  url: jdbc:mysql://123.56.153.56:3306/db_film2?useUnicode=true&characterEncoding=UTF-8
#    url: jdbc:mysql://localhost:3306/db_film2?useUnicode=true&characterEncoding=UTF-8
    url: jdbc:mysql://47.95.221.13:3306/db_film2?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 18142513872
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    cache: false
    prefix: classpath:/templates/

imageFilePath: \src\main\resources\static\filmImages\

catImageFilePath: \src\main\resources\static\catImages\
